#!/bin/bash

#./install_custom/install_gcc.sh 13.2.0
#./install_custom/install_gcc.sh 13.1.0
#./install_custom/install_gcc.sh 12.3.0
#./install_custom/install_gcc.sh 12.2.0
#./install_custom/install_gcc.sh 12.1.0
#./install_custom/install_gcc.sh 11.4.0
#./install_custom/install_gcc.sh 11.3.0
#./install_custom/install_gcc.sh 11.2.0
#./install_custom/install_gcc.sh 11.1.0
#./install_custom/install_gcc.sh 10.5.0
#./install_custom/install_gcc.sh 10.4.0
#./install_custom/install_gcc.sh 10.3.0
#./install_custom/install_gcc.sh 10.2.0
#./install_custom/install_gcc.sh 10.1.0
#./install_custom/install_gcc.sh 9.5.0
#./install_custom/install_gcc.sh 9.4.0
#./install_custom/install_gcc.sh 9.3.0
#./install_custom/install_gcc.sh 9.2.0
#./install_custom/install_gcc.sh 9.1.0
#./install_custom/install_gcc.sh 8.5.0
#./install_custom/install_gcc.sh 8.4.0
#./install_custom/install_gcc.sh 8.3.0
#./install_custom/install_gcc.sh 8.2.0
#./install_custom/install_gcc.sh 8.1.0
#./install_custom/install_gcc.sh 7.5.0
#./install_custom/install_gcc.sh 7.4.0
#./install_custom/install_gcc.sh 7.3.0
#./install_custom/install_gcc.sh 7.2.0
#./install_custom/install_gcc.sh 7.1.0
#./install_custom/install_gcc.sh 6.5.0
#./install_custom/install_gcc.sh 6.4.0
#./install_custom/install_gcc.sh 6.3.0
#./install_custom/install_gcc.sh 6.2.0
#./install_custom/install_gcc.sh 6.1.0
#./install_custom/install_gcc.sh 5.5.0
#./install_custom/install_gcc.sh 5.4.0
#./install_custom/install_gcc.sh 5.3.0
#./install_custom/install_gcc.sh 5.2.0
#./install_custom/install_gcc.sh 5.1.0
#./install_custom/install_gcc.sh 4.9.4
#./install_custom/install_gcc.sh 4.9.3
#./install_custom/install_gcc.sh 4.9.2
#./install_custom/install_gcc.sh 4.9.1
#./install_custom/install_gcc.sh 4.9.0
#./install_custom/install_gcc.sh 4.8.5
#./install_custom/install_gcc.sh 4.8.4
#./install_custom/install_gcc.sh 4.8.3
#./install_custom/install_gcc.sh 4.8.2
#./install_custom/install_gcc.sh 4.8.1
#./install_custom/install_gcc.sh 4.8.0
#./install_custom/install_gcc.sh 4.7.4
#./install_custom/install_gcc.sh 4.7.3
#./install_custom/install_gcc.sh 4.7.2
#./install_custom/install_gcc.sh 4.7.1
./install_custom/install_gcc.sh 4.7.0

